const resources = {
    'zh-TW': {
        translation: {
            line_card_header_version: '版本.',
            line_card_header_export: '匯出',
            line_message_header_unread_message_count: '未讀訊息數量',
            line_message_channel_viewport_height: '訊息視窗高度',
            line_message_body_read: '已讀',
            site_disclaimer: '免責聲明',
            site_disclaimer_content:
                '本網站（以下稱「本網站」）提供之工具僅供娛樂用途，任何人使用本網站所生成的內容，應自負責任。本網站不支持、不鼓勵亦不參與任何形式的欺詐、騙局或其他非法行為。\n使用者理解並同意，不得利用本網站製作、傳播或散播虛假或誤導信息，以進行詐騙、騷擾、誹謗或其他不正當行為。如因使用本網站生成內容而導致任何法律責任或糾紛，本網站及其開發者概不負責。\n本網站保留隨時修改或終止服務的權利，而無需另行通知。\n',
            site_disclaimer_confirm: '理解並同意',
        },
    },
    en: {
        translation: {
            line_card_header_version: 'Version.',
            line_card_header_export: 'Export',
            line_message_header_unread_message_count: 'Unread Message Count',
            line_message_channel_viewport_height: 'Message Window Height',
            line_message_body_read: 'Read',
            site_disclaimer: 'Disclaimer',
            site_disclaimer_content:
                "This website (hereinafter referred to as 'the Website') provides tools for entertainment purposes only. Any content generated using the Website is the sole responsibility of the user. The Website does not support, encourage, or participate in any form of fraud, deception, or other illegal activities.\nUsers understand and agree that they shall not use the Website to create, distribute, or spread false or misleading information to commit fraud, harassment, defamation, or any other improper conduct. The Website and its developers shall not be held liable for any legal responsibilities or disputes arising from the use of content generated by the Website.\nThe Website reserves the right to modify or terminate the service at any time without prior notice.\n",
            site_disclaimer_confirm: 'Understand and Agree',
        },
    },
};

module.exports = resources;
